name: inject
version: 1.1.1
description: Compile-time dependency injection for Dart
authors:
    - Matan Lurey <matanl@google.com>
    - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
    sdk: '>=2.9.1 <3.0.0'

dependencies:
    meta: ^1.3.0
