name: inject
version: 1.1.3
description: Compile-time dependency injection for Dart
homepage: https://pub.dartlang.org/packages/inject

environment:
    sdk: ">=2.19.0 <3.0.0"

dependencies:
    meta: "^1.7.0"
