name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
    - Matan Lurey <matanl@google.com>
    - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
    sdk: '>=2.9.1 <3.0.0'

dependencies:
    analyzer: ^1.1.0
    build: ^2.0.0
    code_builder: ^3.7.0
    collection: ^1.15.0
    dart_style: ^1.3.14
    logging: ^1.0.0
    meta: ^1.3.0
    path: ^1.8.0
    quiver: ^2.0.0
    stack_trace: ^1.10.0

dev_dependencies:
    build_runner: ^1.12.1
    build_test: ^2.0.0
    inject:
        path: ../inject
    test: ^1.16.8
