name: inject.example.coffee
description: A simple example of using package:inject

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
    inject:
        path: ../../package/inject

dev_dependencies:
    build_runner: ^1.12.2
    build_test: ^2.0.0
    build_web_compilers: ^2.16.5
    inject_generator:
        path: ../../package/inject_generator
    test: ^1.16.8
